package bench_test

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"flag"
	"fmt"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/Raj-glitch-max/atlas/internal/record"
	"github.com/Raj-glitch-max/atlas/internal/revstatus"
)

var report = flag.Bool("report", false, "write a TrustPerf RESULTS.md from a measured run")

// TestTrustPerfReport runs the substrate-independent measurements and writes a
// reproducible report. Numbers are environment-specific (labeled as such);
// reproduce with `go test ./atlas-lab/bench -run TestTrustPerfReport -report`.
func TestTrustPerfReport(t *testing.T) {
	if !*report {
		t.Skip("run with -report to (re)generate RESULTS.md")
	}
	r := newRig(t)

	issue := testing.Benchmark(BenchmarkIssue)
	integ := testing.Benchmark(BenchmarkValidateIntegrity)
	accept := testing.Benchmark(BenchmarkVerifyAccept)
	revoked := testing.Benchmark(BenchmarkVerifyRevoked)

	// Proof size: the record bytes on the wire.
	proofSize := len(r.record)

	// Signed revoked-set snapshot size vs N (honest estimate: sum of instance
	// id bytes + one ECDSA signature + timestamp/list overhead).
	key, _ := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	pub, _ := revstatus.NewPublisher(key, "bench-list")
	snapshotRow := func(n int) string {
		revoked := make([]record.InstanceID, n)
		total := 0
		for i := range revoked {
			id, _ := record.InstanceIDFromString("inst-" + itoa(i))
			revoked[i] = id
			total += len(id.String())
		}
		set, _ := pub.Publish(revoked, benchNow)
		approx := total + len(set.Sig) + len(set.ListID) + 8
		return fmt.Sprintf("| %d | %d | %d |", n, len(set.Revoked), approx)
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# TrustPerf results (reference run)\n\n")
	fmt.Fprintf(&b, "> Generated by `go test ./atlas-lab/bench -run TestTrustPerfReport -report` on %s.\n", time.Now().UTC().Format(time.RFC3339))
	fmt.Fprintf(&b, "> Numbers are **environment-specific and indicative** — reproduce on your own hardware. Go %s.\n\n", goVersion())
	fmt.Fprintf(&b, "## Substrate-independent metrics (measured against the real implementation)\n\n")
	fmt.Fprintf(&b, "| operation | latency (ns/op) | throughput (ops/sec) | B/op | allocs/op |\n")
	fmt.Fprintf(&b, "|---|--:|--:|--:|--:|\n")
	row := func(name string, r testing.BenchmarkResult) {
		ns := float64(r.NsPerOp())
		ops := 0.0
		if ns > 0 {
			ops = 1e9 / ns
		}
		fmt.Fprintf(&b, "| %s | %d | %s | %d | %d |\n", name, r.NsPerOp(), commas(int64(ops)), bPerOp(r), allocsPerOp(r))
	}
	row("issue (Seal)", issue)
	row("validate integrity", integ)
	row("verify → Accept", accept)
	row("verify → Reject (revoked)", revoked)

	fmt.Fprintf(&b, "\n## Proof size\n\n- delegation record (compact JWS, ES256): **%d bytes**\n", proofSize)

	fmt.Fprintf(&b, "\n## Signed revoked-set snapshot size vs. revocations\n\n")
	fmt.Fprintf(&b, "| revoked instances | entries | approx bytes |\n|--:|--:|--:|\n")
	fmt.Fprintln(&b, snapshotRow(100))
	fmt.Fprintln(&b, snapshotRow(1000))
	fmt.Fprintln(&b, snapshotRow(10000))
	fmt.Fprintf(&b, "\n(The signed-set realization is O(revoked) in size; the OAuth-Status-List bitfield optimization — deferred — is O(issued/8) and constant per query. See internal/revstatus.)\n")

	fmt.Fprintf(&b, "\n## NOT measured here (require the SPIRE substrate — atlas-lab/experiments, real Docker host)\n\n")
	for _, m := range []string{
		"revocation propagation latency (publish → RP observes)",
		"partition behavior / S4 eventual-upon-recovery bound",
		"cross-domain verification (two independent SPIRE deployments)",
		"zero-egress proof during verification (packet capture)",
		"cold start / warm start of a real node",
		"key rotation propagation",
	} {
		fmt.Fprintf(&b, "- %s\n", m)
	}
	fmt.Fprintf(&b, "\nNo number is fabricated for these; they await a real host.\n")

	if err := os.WriteFile("RESULTS.md", []byte(b.String()), 0o644); err != nil {
		t.Fatal(err)
	}
	t.Logf("wrote RESULTS.md")
}

func bPerOp(r testing.BenchmarkResult) int64 {
	if r.N == 0 {
		return 0
	}
	return int64(r.MemBytes) / int64(r.N)
}

func allocsPerOp(r testing.BenchmarkResult) int64 {
	if r.N == 0 {
		return 0
	}
	return int64(r.MemAllocs) / int64(r.N)
}

func goVersion() string {
	if v, ok := os.LookupEnv("GOVERSION"); ok {
		return v
	}
	return "go (see toolchain)"
}

func commas(n int64) string {
	s := itoa(int(n))
	if len(s) <= 3 {
		return s
	}
	var out []byte
	pre := len(s) % 3
	if pre > 0 {
		out = append(out, s[:pre]...)
	}
	for i := pre; i < len(s); i += 3 {
		if len(out) > 0 {
			out = append(out, ',')
		}
		out = append(out, s[i:i+3]...)
	}
	return string(out)
}

// checkpoint: feat(lab): add Pre-commit validation scripts
